// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrgtlmpuojrvnjqxxuar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyZ3RsbXB1b2pydm5qcXh4dWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDQ5NjEsImV4cCI6MjA1NzYyMDk2MX0.HvAOEZf5zcv4zYYmpHc5LpEKxwS5dKOktDpsYb2GKmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);